version: "3.3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: loja
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data


  app:
    build:
      context: .
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./templates:/app/templates

volumes:
  pg_data:
